# Generated by Django 4.2.7 on 2025-11-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único identificador del local', max_length=20, unique=True, verbose_name='Código del local')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del local')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('responsable_nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del responsable')),
                ('responsable_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del responsable')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['codigo'],
            },
        ),
    ]
