# Generated by Django 4.2.7 on 2025-11-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAveria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tiempo_sla_horas', models.IntegerField(default=24, help_text='Tiempo máximo de respuesta en horas', verbose_name='Tiempo SLA (horas)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal (#RRGGBB)', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Categoría de avería',
                'verbose_name_plural': 'Categorías de averías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('es_interno', models.BooleanField(default=False, help_text='Los comentarios internos no son visibles para digitadores', verbose_name='Comentario interno')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de ticket')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción del problema')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación')),
                ('fecha_inicio_trabajo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio de trabajo')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('fecha_limite_sla', models.DateTimeField(editable=False, verbose_name='Fecha límite SLA')),
                ('solucion', models.TextField(blank=True, null=True, verbose_name='Solución aplicada')),
                ('foto_reparacion', models.ImageField(blank=True, null=True, upload_to='fotos_reparaciones/%Y/%m/', verbose_name='Foto de la reparación')),
                ('notificacion_enviada', models.BooleanField(default=False, verbose_name='Notificación enviada')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
                'permissions': [('puede_asignar_tickets', 'Puede asignar tickets'), ('puede_cerrar_tickets', 'Puede cerrar tickets')],
            },
        ),
    ]
