# Generated by Django 4.2.7 on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='notificacion_sla_enviada',
            field=models.BooleanField(default=False, verbose_name='Notificación SLA enviada'),
        ),
    ]
