# Generated by Django 4.2.7 on 2026-03-04 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_ticket_notificacion_sla_enviada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos_tickets/%Y/%m/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción breve de la imagen (opcional)', max_length=200, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('subida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Subida por')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Imagen de ticket',
                'verbose_name_plural': 'Imágenes de tickets',
                'ordering': ['fecha_subida'],
            },
        ),
    ]
