# Generated by Django 4.2.7 on 2025-11-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='especialidades',
            field=models.ManyToManyField(blank=True, help_text='Tipos de avería que este técnico puede atender (PC, Internet, Electricidad, etc.).', related_name='tecnicos_especialistas', to='tickets.categoriaaveria', verbose_name='Especialidades (tipos de avería)'),
        ),
    ]
